# -*- coding: utf-8 -*-
"""Important_Parts_Endsem.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zXuyqNZV6ecIjkhC_nab4Pk1ksUsrfXe

# A* for Maze Navigation
"""

import heapq

# 1. The Adjacency List (Topology)
maze4 = {
    'S': ['A', 'B'],
    'A': ['S', 'C', 'D'],
    'B': ['S', 'D', 'E'],
    'C': ['A'],
    'D': ['A', 'B', 'G'],
    'E': ['B'],
    'G': ['D']
}

# 2. The Coordinate Dictionary (Geometry - (x, y) coordinates)
maze4_coords = {
    'S': (0, 0),
    'A': (1, 0),
    'B': (0, 1),
    'C': (2, 0),
    'D': (1, 1),
    'E': (0, 2),
    'G': (2, 2)
}

start_node = 'S'
goal_node = 'G'
visited = set()


#=======================================================================#


def manh_dist(curr, goal):
    xc, yc = maze4_coords[curr]
    xg, yg = maze4_coords[goal]
    return abs(xg - xc) + abs(yg - yc)


#=======================================================================#


def a_star_maze(start, goal, maze, coords):
    # Get the manh of the start node
    start_manh = manh_dist(start, goal)
    # Make the start node a path as g(n) = len of path - 1 and we will need g(n) to push
    start_path = [start]
    # Calculate the f(n) for start
    # g(n) = len of path - 1
    # h(n) = manh dist
    # f(n) = g(n) + h(n)
    start_fn = start_manh + len(start_path) -  1
    # Initialzie a pq
    pq = []
    # Push start to pq
    heapq.heappush(pq, (start_fn, start_path))
    # Nodes expanded counter
    nodes_expanded = 0

    # Interatively handle items in the pq
    while pq:
        # Get the topmost ele
        fn, curr_path = heapq.heappop(pq)
        # Get the current node
        curr_node = curr_path[-1]

        # Check if the current node is goal
        if curr_node == goal:
            return curr_path, nodes_expanded

        # If node hasn't been already visited, process it:
        if curr_node not in visited:
            # Visit the node
            visited.add(curr_node)
            # Expand the node
            nodes_expanded += 1

            # Iteratively handle all neighbours
            for neighbour in maze[curr_node]:
                # Create new path - copy of curr path - to append the neighbour
                new_path = list(curr_path)
                # Append the new node to the new_path
                new_path.append(neighbour)
                # Calculate g(n), h(n), f(n)
                gn = len(new_path) - 1
                hn = manh_dist(curr_node, goal)
                fn = gn + hn
                # Push
                heapq.heappush(pq, (fn, new_path))

    return None, nodes_expanded


#=======================================================================#


path, nodes_expanded = a_star_maze(start_node, goal_node, maze4, maze4_coords)

if path:
  print(f"Path: {path}, Nodes expanded: {nodes_expanded}")
else:
  print(f"No Path found")

"""# BFS for 8-Puzzle Problem"""

from collections import deque

init_state = (1, 2, 3,
              4, 0, 5,
              6, 7, 8)

goal_state = (1, 2, 3,
              4, 5, 6,
              7, 8, 0)


#=======================================================================#

def get_valid_moves(idx):
    moveset = []

    # UP move can be performed as long as the agent is not in top row
    # For up, do idx - 3
    if idx > 2:
        moveset.append(-3)
    # DOWN move can be performed as long as the agent is not in the btm row
    # For DOWN, do idx + 3
    if idx < 6:
        moveset.append(3)
    # LEFT can be done if agent is not in leftmost col already
    # For LEFT do idx - 1
    if idx not in [0, 3, 6]:
        moveset.append(-1)
    # RIGHT can be done if the agent is not in rightmost col already
    # For RIGHT do idx + 1
    if idx not in [2, 5, 8]:
        moveset.append(1)

    return moveset


#=======================================================================#


def bfs_8_puzzle(start, goal):
    # Instantiate a visited set
    visited = set()
    # Instantiate a deque
    dq = deque()
    # Append the start state to the dq - pass it as a list
    # Here each **tuple** (not a single number) is a node
    # And the deque as always stores paths which in this case are lists containing tuples
    dq.append([start])
    # Keep a track of the nodes expanded
    nodes_expanded = 0

    # Iteratively handle paths in the dq
    while dq:
        # Fetch the current path
        path = dq.popleft()
        # Fetch the current node
        node = path[-1]

        # Check if the node is the goal
        if node == goal:
            return path, nodes_expanded

        # If the node is not goal, check if it has been already visited
        if node not in visited:
            # Since we visited the node now, add it to visited
            visited.add(node)
            # Add count to nodes expanded
            nodes_expanded += 1
            # Get the index where 0 is present in the node - for neighbour calc
            zero_idx = node.index(0)
            # Get the valid moves list for the idx
            moves = get_valid_moves(zero_idx)

            # Iteratively perform all moves (same as visiting all neighbours)
            # To perform a move, you will have to swap the ele in new index with 0
            # To do this, convert tuple to list first
            # After performing swap/move, convert list back to tuple and append to path
            for move in moves:
                # convert to list
                new_node = list(node)
                # Calculate new idx: zero_idx + move
                new_idx = zero_idx + move
                # perform swap
                new_node[new_idx], new_node[zero_idx] = new_node[zero_idx], new_node[new_idx]
                # Convert the list back to a tuple
                new_node = tuple(new_node)
                # Add the new node to a new path which is a copy of the current path
                new_path = list(path)
                # Append new node to new path
                new_path.append(new_node)
                # Append new path to sq
                dq.append(new_path)

    return None, nodes_expanded


#=======================================================================#


history, nodes_expanded = bfs_8_puzzle(init_state, goal_state)

if history:
  print(f"Path:")
  for i in history:
    print(f"{i}")
  print(f"Nodes expanded: {nodes_expanded}")
else:
  print(f"No possible path")


#=======================================================================#

"""# A* for Maze Navigation"""

import heapq

# 1. The Adjacency List (Topology)
maze4 = {
    'S': ['A', 'B'],
    'A': ['S', 'C', 'D'],
    'B': ['S', 'D', 'E'],
    'C': ['A'],
    'D': ['A', 'B', 'G'],
    'E': ['B'],
    'G': ['D']
}

# 2. The Coordinate Dictionary (Geometry - (x, y) coordinates)
maze4_coords = {
    'S': (0, 0),
    'A': (1, 0),
    'B': (0, 1),
    'C': (2, 0),
    'D': (1, 1),
    'E': (0, 2),
    'G': (2, 2)
}

start_node = 'S'
goal_node = 'G'
visited = set()


#=======================================================================#


def manh_dist(curr, goal):
    xc, yc = maze4_coords[curr]
    xg, yg = maze4_coords[goal]
    return abs(xg - xc) + abs(yg - yc)


#=======================================================================#


def a_star_maze(start, goal, maze, coords):
    # Get the manh of the start node
    start_manh = manh_dist(start, goal)
    # Make the start node a path as g(n) = len of path - 1 and we will need g(n) to push
    start_path = [start]
    # Calculate the f(n) for start
    # g(n) = len of path - 1
    # h(n) = manh dist
    # f(n) = g(n) + h(n)
    start_fn = start_manh + len(start_path) -  1
    # Initialzie a pq
    pq = []
    # Push start to pq
    heapq.heappush(pq, (start_fn, start_path))
    # Nodes expanded counter
    nodes_expanded = 0

    # Interatively handle items in the pq
    while pq:
        # Get the topmost ele
        fn, curr_path = heapq.heappop(pq)
        # Get the current node
        curr_node = curr_path[-1]

        # Check if the current node is goal
        if curr_node == goal:
            return curr_path, nodes_expanded

        # If node hasn't been already visited, process it:
        if curr_node not in visited:
            # Visit the node
            visited.add(curr_node)
            # Expand the node
            nodes_expanded += 1

            # Iteratively handle all neighbours
            for neighbour in maze[curr_node]:
                # Create new path - copy of curr path - to append the neighbour
                new_path = list(curr_path)
                # Append the new node to the new_path
                new_path.append(neighbour)
                # Calculate g(n), h(n), f(n)
                gn = len(new_path) - 1
                hn = manh_dist(curr_node, goal)
                fn = gn + hn
                # Push
                heapq.heappush(pq, (fn, new_path))

    return None, nodes_expanded


#=======================================================================#


path, nodes_expanded = a_star_maze(start_node, goal_node, maze4, maze4_coords)

if path:
  print(f"Path: {path}, Nodes expanded: {nodes_expanded}")
else:
  print(f"No Path found")


#=======================================================================#

"""# IDA* for Maze Navigation"""

import heapq

# 1. The Adjacency List (Topology)
maze4 = {
    'S': ['A', 'B'],
    'A': ['S', 'C', 'D'],
    'B': ['S', 'D', 'E'],
    'C': ['A'],
    'D': ['A', 'B', 'G'],
    'E': ['B'],
    'G': ['D']
}

# 2. The Coordinate Dictionary (Geometry - (x, y) coordinates)
maze4_coords = {
    'S': (0, 0),
    'A': (1, 0),
    'B': (0, 1),
    'C': (2, 0),
    'D': (1, 1),
    'E': (0, 2),
    'G': (2, 2)
}

start_node = 'S'
goal_node = 'G'
visited = set()


#=======================================================================#


def manh_dist(curr, goal):
    xc, yc = maze4_coords[curr]
    xg, yg = maze4_coords[goal]
    return abs(xg - xc) + abs(yg - yc)


#=======================================================================#


def search(curr_path, g, threshold, goal, maze, nodes_expanded):
    """
    Recursive DFS that explores paths up to a specific f-cost threshold.
    Returns: (Result, updated_nodes_expanded)
    Result can be "FOUND" or the min f-cost that exceeded the threshold.
    """
    # The curr node that we are evaluating is the last node in the path
    curr_node = curr_path[-1]

    # Calculate f(n) = g(n) + h(n)
    f = g + manh_dist(curr_node, goal)

    # 1. Base case: Threshold exceeded
    # If this node's cost is too high, prune it
    # We return 'f' so that the outer loop knows what to increase the threshold to next time
    if f > threshold:
        return f, nodes_expanded

    # 2. Base case: Goal Found
    if curr_node == goal:
        return "FOUND", nodes_expanded

    # 3. Recursive DFS expansion
    # We need to track the lowest cost among all pruned branches
    # So we will start with a very high min cost so that it gets updated easily
    min_cost = float('inf')

    for neighbour in maze[curr_node]:
        # Mem efficient cycle prevention: only check current path
        if neighbour not in curr_path:
            # Expand node
            curr_path.append(neighbour)
            nodes_expanded += 1

            # Recursive step: g always increases by 1 when a node is expanded
            result, nodes_expanded = search(curr_path, g+1, threshold, goal, maze, nodes_expanded)

            # If the recursive call found goal, unwind stack immediately
            if result == "FOUND":
                return "FOUND", nodes_expanded

            # If not found update the min_cost with the pruned value
            if result < min_cost:
                min_cost = result

            # BACTRACK: Remove neighbour before trying next one
            curr_path.pop()

    return min_cost, nodes_expanded


#=======================================================================#


def ida_star_maze(start, goal, maze, coords):
    # Initialize the starting threshold: f(start) = g(start) + h(start)
    # Since we are at the start, g = 0, so f = h
    threshold = manh_dist(start, goal)
    nodes_expanded = 0

    # 2. The Iterative Deepening Loop
    while True:
        # We start a fresh dfs with just the start node in our path
        curr_path = [start]

        # Run the search algo from prev section
        result, nodes_expanded = search(curr_path, 0, threshold, goal, maze, nodes_expanded)

        # 3. Evaluate the DFS o/p
        if result == "FOUND":
            # Because our search fxn skips curr_path.pop() when it finds the goal,
            # curr_path contains the successful route
            return curr_path, nodes_expanded

        if result == float('inf'):
            # If the min_cost comes back as inf, it means goal was never reached from start
            # i.e. no valid path
            return None, nodes_expanded

        # 4. Increase the threshold for the next iteration
        # 'result' holds the minimum f-cost that exceeded our old threshold
        threshold = result


#=======================================================================#


path, expanded = ida_star_maze(start_node, goal_node, maze4, maze4_coords)

if path:
    print(f"Path found: {path}")
    print(f"Total Nodes Expanded: {expanded}")
else:
    print("No Path found")

"""# IDA* for 8-Puzzle Problem"""

init_state = (1, 2, 3,
              4, 0, 5,
              6, 7, 8)

goal_state = (1, 2, 3,
              4, 5, 6,
              7, 8, 0)


#=======================================================================#


def get_valid_moves(idx):
    moveset = []

    # UP move can be performed as long as the agent is not in top row
    # For up, do idx - 3
    if idx > 2:
        moveset.append(-3)
    # DOWN move can be performed as long as the agent is not in the btm row
    # For DOWN, do idx + 3
    if idx < 6:
        moveset.append(3)
    # LEFT can be done if agent is not in leftmost col already
    # For LEFT do idx - 1
    if idx not in [0, 3, 6]:
        moveset.append(-1)
    # RIGHT can be done if the agent is not in rightmost col already
    # For RIGHT do idx + 1
    if idx not in [2, 5, 8]:
        moveset.append(1)

    return moveset


#=======================================================================#


def manh_dist_8_puzzle(curr_state, goal_state):
    """
    Calculates the total Manhattan distance for the 8-puzzle.
    Converts 1D tuple indices into 2D (row, col) coordinates.
    """
    total_dist = 0
    # We check tiles 1 through 8 (ignoring the blank tile 0)
    for tile in range(1, 9):
        # Find the index in the current state and goal state
        curr_idx = curr_state.index(tile)
        goal_idx = goal_state.index(tile)

        # Convert 1D index to 2D (row, col) coordinates
        # Row = idx // 3, Col = idx % 3
        curr_row, curr_col = curr_idx // 3, curr_idx % 3
        goal_row, goal_col = goal_idx // 3, goal_idx % 3

        # Calculate Manhattan distance for this specific tile
        dist = abs(curr_row - goal_row) + abs(curr_col - goal_col)
        total_dist += dist

    return total_dist


#=======================================================================#


def search_8_puzzle(curr_path, g, threshold, goal, nodes_expanded):
    # 1. Evaluate the current state
    curr_node = curr_path[-1]
    f = g + manh_dist_8_puzzle(curr_node, goal)

    # BAse case 1: cost exceeds the threshold
    if f > threshold:
        return f, nodes_expanded

    # Base case 2: curr node is goal
    if curr_node == goal:
        return "FOUND", nodes_expanded

    min_cost = float('inf')

    # 2. Generate neighbours using the fxn
    zero_idx = curr_node.index(0)
    moves = get_valid_moves(zero_idx)

    for move in moves:
        # Perform swap to get the new state
        new_node_list = list(curr_node)
        # calculate new_idx
        new_idx = zero_idx + move
        # swap
        new_node_list[zero_idx], new_node_list[new_idx] = curr_node[new_idx], curr_node[zero_idx]
        # Tuple
        new_node = tuple(new_node_list)

        if new_node not in curr_path:
            curr_path.append(new_node)
            nodes_expanded += 1

            # Recursive step: g+1
            result, nodes_expanded = search_8_puzzle(curr_path, g+1, threshold, goal, nodes_expanded)

            if result == "FOUND":
                return "FOUND", nodes_expanded

            if result < min_cost:
                min_cost = result

            # BACKTRACK
            curr_path.pop()

    return min_cost, nodes_expanded


#=======================================================================#


def ida_star_8_puzzle(start, goal):
    # Threshold initialized to the heuristic of the start state (gn = 0 here, so fn = hn)
    threshold = manh_dist_8_puzzle(start, goal)
    nodes_expanded = 0

    while True:
        curr_path = [start]
        result, nodes_expanded = search_8_puzzle(curr_path, 0, threshold, goal, nodes_expanded)

        if result == "FOUND":
            return curr_path, nodes_expanded

        if result == float('inf'):
            return None, nodes_expanded

        # INcrease the threshold to match the f-cost
        threshold = result


#=======================================================================#


path, expanded = ida_star_8_puzzle(init_state, goal_state)

if path:
    print(f"Goal reached in {len(path) - 1} moves!")
    print(f"Total Nodes Expanded: {expanded}")
    print("\nStep-by-step path:")
    for step, state in enumerate(path):
        print(f"Step {step}:")
        print(f"{state[0]} {state[1]} {state[2]}")
        print(f"{state[3]} {state[4]} {state[5]}")
        print(f"{state[6]} {state[7]} {state[8]}\n")
else:
    print("No Path found")

"""# SMA* for Maze Navigation

"""

class Node:
    def __init__(self, state, parent=None, g=0, h=0):
        self.state = state
        self.parent = parent
        self.g = g
        self.h = h
        self.f = g + h

        # We need to track children so we know if this node is a leaf
        self.children = []

        # This holds the "backed up" f-cost if a child gets pruned
        self.forgotten_f = float('inf')

    def get_f(self):
        """
        Returns the effective f-cost.
        If this node has forgotten a child, its f-cost is the MINIMUM
        of its normal f-cost and its forgotten child's f-cost.
        """
        # If it has no children in memory, but has a forgotten f-cost,
        # it acts as a proxy for that pruned branch.
        if not self.children and self.forgotten_f != float('inf'):
            return max(self.f, self.forgotten_f)

        # Otherwise, its f-cost is the lowest f-cost of its current children
        if self.children:
            return min([child.get_f() for child in self.children])

        return self.f

    def get_path(self):
        """Helper to trace back to the start node."""
        path = []
        curr = self
        while curr:
            path.append(curr.state)
            curr = curr.parent
        return path[::-1] # Reverse it so it goes Start -> Goal


#===========================================================================#


def sma_star_maze(start, goal, maze, coords, memory_limit=5):
    # Initialize the start node
    start_h = manh_dist(start, goal)
    start_node = Node(state=start, g=0, h=start_h)

    # The frontier holds all our current leaf nodes
    frontier = [start_node]
    nodes_expanded = 0
    current_memory = 1  # We currently have 1 node in memory

    while frontier:
        # 1. Find the BEST node to expand (Lowest f-cost)
        # We sort ascending, so the best node is at index 0
        frontier.sort(key=lambda n: n.get_f())
        best_node = frontier.pop(0)

        # 2. Base Case: Goal Reached
        if best_node.state == goal:
            return best_node.get_path(), nodes_expanded

        # 3. Expand the best node
        nodes_expanded += 1
        path_so_far = best_node.get_path() # For cycle prevention

        for neighbour in maze[best_node.state]:
            if neighbour not in path_so_far:
                child_g = best_node.g + 1
                child_h = manh_dist(neighbour, goal)

                # Create the child and link it to the parent
                child = Node(state=neighbour, parent=best_node, g=child_g, h=child_h)
                best_node.children.append(child)

                # Add child to our active frontier
                frontier.append(child)
                current_memory += 1

        # 4. The SMA* Memory Manager (Pruning)
        # If expanding those neighbors pushed us over the memory limit, we must prune.
        while current_memory > memory_limit:
            # Sort descending, so the WORST node (highest f-cost) is at index 0
            frontier.sort(key=lambda n: n.get_f(), reverse=True)
            worst_node = frontier.pop(0)

            parent = worst_node.parent
            if parent:
                # Remove the worst node from its parent's memory
                parent.children.remove(worst_node)

                # BACKUP COST: The parent remembers the best cost of its forgotten children
                parent.forgotten_f = min(parent.forgotten_f, worst_node.get_f())

                # CRITICAL STEP: If we deleted all of a parent's children,
                # the parent is now a leaf node again! It must go back into the frontier.
                if not parent.children and parent not in frontier:
                    frontier.append(parent)

            # We successfully freed up 1 unit of memory
            current_memory -= 1

    # If the frontier is empty and we haven't found the goal, the maze is impossible
    return None, nodes_expanded


#===========================================================================#


# --- Execution Block ---
# Let's test it with a memory limit of 5 nodes
path, expanded = sma_star_maze(start_node, goal_node, maze4, maze4_coords, memory_limit=5)

if path:
    print(f"SMA* Path found: {path}")
    print(f"Total Nodes Expanded: {expanded}")
else:
    print("No Path found (Memory limit might be too low to reach the goal)")

"""# SMA* for 8-Puzzle Problem"""

class Node:
    def __init__(self, state, parent=None, g=0, h=0):
        self.state = state
        self.parent = parent
        self.g = g
        self.h = h
        self.f = g + h

        # We need to track children so we know if this node is a leaf
        self.children = []

        # This holds the "backed up" f-cost if a child gets pruned
        self.forgotten_f = float('inf')

    def get_f(self):
        """
        Returns the effective f-cost.
        If this node has forgotten a child, its f-cost is the MINIMUM
        of its normal f-cost and its forgotten child's f-cost.
        """
        # If it has no children in memory, but has a forgotten f-cost,
        # it acts as a proxy for that pruned branch.
        if not self.children and self.forgotten_f != float('inf'):
            return max(self.f, self.forgotten_f)

        # Otherwise, its f-cost is the lowest f-cost of its current children
        if self.children:
            return min([child.get_f() for child in self.children])

        return self.f

    def get_path(self):
        """Helper to trace back to the start node."""
        path = []
        curr = self
        while curr:
            path.append(curr.state)
            curr = curr.parent
        return path[::-1] # Reverse it so it goes Start -> Goal



#===========================================================================#


init_state = (1, 2, 3,
              4, 0, 5,
              6, 7, 8)

goal_state = (1, 2, 3,
              4, 5, 6,
              7, 8, 0)


#===========================================================================#


def get_valid_moves(idx):
    moveset = []

    # UP move can be performed as long as the agent is not in top row
    # For up, do idx - 3
    if idx > 2:
        moveset.append(-3)
    # DOWN move can be performed as long as the agent is not in the btm row
    # For DOWN, do idx + 3
    if idx < 6:
        moveset.append(3)
    # LEFT can be done if agent is not in leftmost col already
    # For LEFT do idx - 1
    if idx not in [0, 3, 6]:
        moveset.append(-1)
    # RIGHT can be done if the agent is not in rightmost col already
    # For RIGHT do idx + 1
    if idx not in [2, 5, 8]:
        moveset.append(1)

    return moveset


#===========================================================================#


def manh_dist_8_puzzle(curr_state, goal_state):
    """
    Calculates the total Manhattan distance for the 8-puzzle.
    Converts 1D tuple indices into 2D (row, col) coordinates.
    """
    total_dist = 0
    # We check tiles 1 through 8 (ignoring the blank tile 0)
    for tile in range(1, 9):
        # Find the index in the current state and goal state
        curr_idx = curr_state.index(tile)
        goal_idx = goal_state.index(tile)

        # Convert 1D index to 2D (row, col) coordinates
        # Row = idx // 3, Col = idx % 3
        curr_row, curr_col = curr_idx // 3, curr_idx % 3
        goal_row, goal_col = goal_idx // 3, goal_idx % 3

        # Calculate Manhattan distance for this specific tile
        dist = abs(curr_row - goal_row) + abs(curr_col - goal_col)
        total_dist += dist

    return total_dist


#===========================================================================#


def sma_star_8_puzzle(start_state, goal_state, memory_limit=50):
    # 1. Initialize the start node using our Manhattan distance heuristic
    start_h = manh_dist_8_puzzle(start_state, goal_state)
    start_node = Node(state=start_state, g=0, h=start_h)

    frontier = [start_node]
    nodes_expanded = 0
    current_memory = 1

    while frontier:
        # Sort ascending to get the best node (lowest f-cost)
        frontier.sort(key=lambda n: n.get_f())
        best_node = frontier.pop(0)

        # Base Case: Goal Reached
        if best_node.state == goal_state:
            return best_node.get_path(), nodes_expanded

        nodes_expanded += 1
        path_so_far = best_node.get_path()

        # 2. GENERATE NEIGHBORS (The 8-Puzzle Physics)
        zero_idx = best_node.state.index(0)
        moves = get_valid_moves(zero_idx)

        for move in moves:
            # Swap the tiles to create the new state
            new_state_list = list(best_node.state)
            new_idx = zero_idx + move
            new_state_list[zero_idx], new_state_list[new_idx] = new_state_list[new_idx], new_state_list[zero_idx]
            child_state = tuple(new_state_list)

            # Cycle prevention
            if child_state not in path_so_far:
                child_g = best_node.g + 1 # Uniform step cost = 1
                child_h = manh_dist_8_puzzle(child_state, goal_state)

                # Create and link the child node
                child = Node(state=child_state, parent=best_node, g=child_g, h=child_h)
                best_node.children.append(child)

                frontier.append(child)
                current_memory += 1

        # 3. SMA* MEMORY MANAGER
        while current_memory > memory_limit:
            # Sort descending to find the worst node (highest f-cost)
            frontier.sort(key=lambda n: n.get_f(), reverse=True)
            worst_node = frontier.pop(0)

            parent = worst_node.parent
            if parent:
                # Prune the leaf
                parent.children.remove(worst_node)
                # Backup the cost
                parent.forgotten_f = min(parent.forgotten_f, worst_node.get_f())

                # Re-insert parent if it becomes a leaf again
                if not parent.children and parent not in frontier:
                    frontier.append(parent)

            current_memory -= 1

    return None, nodes_expanded


#===========================================================================#


# --- Execution Block ---
# Note: A 5-node memory limit is too small for an 8-puzzle.
# We'll give it a limit of 50, which is still incredibly tiny compared to standard A*!
path, expanded = sma_star_8_puzzle(init_state, goal_state, memory_limit=50)

if path:
    print(f"Goal reached in {len(path) - 1} moves!")
    print(f"Total Nodes Expanded: {expanded}")
    print("\nStep-by-step path:")
    for step, state in enumerate(path):
        print(f"Step {step}:")
        print(f"{state[0]} {state[1]} {state[2]}")
        print(f"{state[3]} {state[4]} {state[5]}")
        print(f"{state[6]} {state[7]} {state[8]}\n")
else:
    print("No Path found (Memory limit might be too low)")

"""# Hill Climbing Algorithm"""

import numpy as np
from sklearn.datasets import load_breast_cancer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
import warnings


#===========================================================================#


# Suppress convergence warnings for clean output
warnings.filterwarnings("ignore")

# 1. Load the Dataset
data = load_breast_cancer()
X_full = data.data    # Shape: (569 samples, 30 features)
y = data.target       # Shape: (569 samples)
num_features = X_full.shape[1]

print(f"Dataset loaded. Total features available: {num_features}")

# 2. The Evaluation Function (Our "Heuristic")
def evaluate_state(state, X, y):
    """
    Takes a binary state vector, filters the dataset to only include
    selected features, and returns the cross-validation accuracy.
    """
    # Convert state to a boolean mask (1 -> True, 0 -> False)
    mask = np.array(state) == 1

    # Edge Case: If the state is all 0s, the model has no features to train on!
    # We return an accuracy of 0 to heavily penalize this state.
    if not np.any(mask):
        return 0.0

    # Filter the dataset columns using the mask
    X_selected = X[:, mask]

    # Initialize a simple Logistic Regression classifier
    model = LogisticRegression(max_iter=1000)

    # Run 5-fold cross-validation and get the average accuracy
    # cv=5 means it splits the data into 5 chunks, trains on 4, tests on 1, and averages the results.
    scores = cross_val_score(model, X_selected, y, cv=5, scoring='accuracy')

    return np.mean(scores)

# Let's test it with a state where ALL features are selected (Baseline)
baseline_state = [1] * num_features
baseline_acc = evaluate_state(baseline_state, X_full, y)
print(f"Baseline Accuracy (All Features): {baseline_acc:.4f}")


#===========================================================================#


def get_neighbors(state):
    """
    Generates all possible neighbors by flipping exactly one bit
    in the current binary state array.
    """
    neighbors = []
    for i in range(len(state)):
        # Create a fresh copy of the current state
        neighbor = list(state)

        # Flip the i-th bit (1 becomes 0, 0 becomes 1)
        neighbor[i] = 1 - neighbor[i]

        neighbors.append(neighbor)

    return neighbors


#===========================================================================#


def steepest_ascent_hill_climbing(X, y, max_iterations=100):
    num_features = X.shape[1]

    # 1. Generate a random initial state (0s and 1s)
    current_state = np.random.randint(2, size=num_features).tolist()

    # Safety check: Prevent starting with an empty feature set
    if sum(current_state) == 0:
        current_state[np.random.randint(num_features)] = 1

    current_score = evaluate_state(current_state, X, y)
    print(f"Initial State Score: {current_score:.4f} (Features used: {sum(current_state)})")

    history = [(current_state, current_score)]

    # 2. The Hill-Climbing Loop
    for iteration in range(max_iterations):
        neighbors = get_neighbors(current_state)

        best_neighbor = None
        best_neighbor_score = -1.0

        # Evaluate every single neighbor (This is the "Steepest" part)
        for neighbor in neighbors:
            score = evaluate_state(neighbor, X, y)
            if score > best_neighbor_score:
                best_neighbor_score = score
                best_neighbor = neighbor

        # 3. The Peak Check
        # If no neighbor beats our current score, we are at a local maximum. Stop climbing.
        if best_neighbor_score <= current_score:
            print(f"Reached a peak at iteration {iteration}! No better neighbors.")
            break

        # 4. Move Uphill
        current_state = best_neighbor
        current_score = best_neighbor_score
        history.append((current_state, current_score))

        print(f"Iteration {iteration+1}: Jumped to new score {current_score:.4f} (Features used: {sum(current_state)})")

    return current_state, current_score, history


#===========================================================================#


# --- Execution Block ---
best_state, best_score, climb_history = steepest_ascent_hill_climbing(X_full, y)

print("\n--- Final Results ---")
print(f"Best Accuracy: {best_score:.4f}")
print(f"Optimal Number of Features: {sum(best_state)} out of {num_features}")

"""# Q-Learning Warehouse Agent
---

```
1. env: init(grid_size),
        reset(),
        step(action)
2. agent: init(env, alpha, gamma, epsilon, min_epsilon, epsilon_decay),
          get_action(state),
          learn(state, action, reward, next_state),
          decay_epsilon()
In loop: OUTSIDE - num episodes
         current_state = reset env
         done = False
         total_reward = 0
         step count = 0
         num_steps = 500
         INSIDE - num steps - loop
         action = agent.get_action(curr_state)
         reward, next_state, done = env.step(action)
         agent.learn(current_state, action, reward, next_state)
         current_state = next_state
         total_reward += reward
         step_count += 1
         OUTSIDE - num episodes - loop
         agent.decay_epsilon()
         reward_history.append(total_reward)
```


"""

# Env Setup
import numpy as np
import random

class WarehouseEnv:
    def __init__(self, grid_size=5):
        self.grid_size = grid_size
        self.start_state = (0, 0)
        self.goal_state = (4, 4)

        # create few obstacles (hard-coded)
        self.obstacles = [(1, 1), (2, 2), (3, 1)]

        # self.state hold the current state/location of the agent
        # At the start (init), the agent is at the start position (0, 0)
        # Hence we set it to self.start_state at the beginning
        # In the later parts of the code, it's used to store the curr state/locn
        self.state = self.start_state # what was the purpose of this?

        # actions: 0: up, 1: down, 2: left, 3: right
        self.action_space = [0, 1, 2, 3]

    def reset(self):
        """Resets the agent to the start state at the start of a new episode"""
        self.state = self.start_state
        return self.state

    def step(self, action):
        """
        Takes an action, updates the state and calculates the reward
        Returns: (next_state, reward, done_flag)
        """

        # Get current state coords
        r, c = self.state

        # 1. Calculate the tentative new position
        if action == 0: # up
            r = max(0, r - 1)
        if action == 1: # down
            r = min(self.grid_size - 1, r + 1)
        if action == 2: # left
            c = max(0, c - 1)
        if action == 3: # right
            c = min(self.grid_size - 1, c + 1)

        next_state = (r, c)

        # 2. Check collision with obstacles
        if next_state in self.obstacles:
            # Hit an obstacle, bounce back to the original state, get -ve reward
            next_state = self.state
            reward = -10
            done = False
        # 3. Check if goal achieved
        elif next_state == self.goal_state:
            # Reached goal, give massive reward, end episode
            reward = 100
            done = True
        # 4. Handle normal case
        else:
            # Normal movement, give small -ve reward to force exploration
            reward = -1
            done = False

        # 5. Update internal state
        self.state = next_state

        # Return (next_state i.e. updated state, reward, done flag)
        return next_state, reward, done


#========================================================================#


class QLearningAgent:
    def __init__(self, env, alpha=0.1, gamma=0.9, epsilon=1.0,
                 epsilon_decay=0.995, min_epsilon=0.01):
        self.env = env
        self.alpha = alpha     # Learning rate
        self.gamma = gamma     # Discount factor (important for future rewards)
        self.epsilon = epsilon # Initial exploration rate (1.0 = 100% random)
        self.epsilon_decay = epsilon_decay
        self.min_epsilon = min_epsilon

        # Initialize the Q-table: a dict mapping (r, c) -> array of 4 Q-values
        self.q_table = {}
        # Iterate over rows
        for r in range(env.grid_size):
            # Iterate over cols
            for c in range(env.grid_size):
                # for (r,c) key, store an array containing 4 zeros
                self.q_table[(r, c)] = np.zeros(len(env.action_space))

    def choose_action(self, state):
        """Epsilon-greedy action selection"""
        # EXPLORE: Roll a random number: If it is less than epsilon,
        # pick a random action
        if random.uniform(0, 1) < self.epsilon:
            return random.choice(self.env.action_space)
        # EXPLOIT : Otherwise, refer the Q-table and pick the action with
        # the largest Q-value
        else:
            return np.argmax(self.q_table[state])

    def learn(self, state, action, reward, next_state):
        """Updates the Q-table using Bellman Equation"""
        # 1. Look ahead to the next state and find the highest possible Q-value
        best_next_action_value = np.max(self.q_table[next_state])

        # 2. Calculate what the Q-value *should* be (the temporal diff target)
        td_target = reward + (self.gamma * best_next_action_value)

        # 3. Calculate the error between old guess and the new target
        td_error = td_target - self.q_table[state][action]

        # 4. Update the Q-Table incrementally using the learning rate (alpha)
        self.q_table[state][action] += self.alpha * td_error

    def decay_epsilon(self):
        """Gradually reduce the exploration to transition into exploitation"""
        self.epsilon = max(self.min_epsilon, self.epsilon * self.epsilon_decay)


#========================================================================#


# 1. Initialize the agent
env = WarehouseEnv(grid_size=5)
agent = QLearningAgent(env, alpha=0.1, gamma=0.9, epsilon=1.0)

num_eps = 500
rewards_history = []

# 2. The outer loop - episodes
for ep in range(num_eps):
    # Reset env for a fresh start every episode
    # env.reset() returns the start state (0, 0)
    current_state = env.reset()
    total_reward = 0
    done = False

    # 3. The inner loop - steps within an episode
    # We add a safety counter to prevent infinite wandering
    step_count = 0
    max_steps = 1000

    while not done and step_count < max_steps:
        # Agent looks at the current state and decides what to do
        action = agent.choose_action(current_state)

        # The env processes the action and generates the results
        next_state, reward, done = env.step(action)

        # The agent updates its Q-Table based on what just happened
        agent.learn(current_state, action, reward, next_state)

        # Update state - move agent to new state
        current_state = next_state
        total_reward += reward
        step_count += 1

    # At the end of episode, decay epsilon
    agent.decay_epsilon()

    # Record the performance
    rewards_history.append(total_reward)


#========================================================================#


# 5. Let's see the final learned policy (The brain dump)
print("\nFinal Learned Policy (Best action for each cell):")
actions_dict = {0: 'Up', 1: 'Down', 2: 'Left', 3: 'Right'}

for r in range(env.grid_size):
    row_policy = []
    for c in range(env.grid_size):
        if (r, c) == env.goal_state:
            row_policy.append("[GOAL]")
        elif (r, c) in env.obstacles:
            row_policy.append("[WALL]")
        else:
            best_action_idx = np.argmax(agent.q_table[(r, c)])
            row_policy.append(f"{actions_dict[best_action_idx]:<5}")
    print(" | ".join(row_policy))


#========================================================================#


import matplotlib.pyplot as plt

# 4. Visualize the Learning Curve
plt.figure(figsize=(10, 5))
plt.plot(rewards_history, color='blue', alpha=0.7)
plt.title('Q-Learning Performance over Time')
plt.xlabel('Episode')
plt.ylabel('Total Reward')
plt.grid(True)
plt.show()

"""# K-Armed Bandit Advertisement"""

import numpy as np

class AdBanditEnv:
    def __init__(self, k_arms=5):
        self.k = k_arms

        # Assign randomly generated probabilities for the ads getting clicked
        # This info is kept hidden from the agent
        # we use np.random.uniform because base random.uniform can't produce an array of values
        self.true_action_values = np.random.uniform(0.5, 0.8, self.k)

        # Print the true values
        print(f"True probs: {self.true_action_values}")
        print(f"Best Ad: {np.argmax(self.true_action_values)}")

    def step(self, action):
        """
        Shows the ad to the user and returns if they clicked it.
        action: The ad that the agent decided to show
        returns: Reward = 1.0 if user clicks as, Reward = 0.0 if user ignores
        """
        # Get the probability of the ad
        click_probability = self.true_action_values[action]

        # Roll a number between 0 and 1
        # If its less than the ad's click prob, user clicks it (reward = 1)
        # Otherwise, they ignored it (reward = 0)
        if np.random.random() < click_probability:
            return 1.0 # Clicked
        else:
            return 0.0 # Ignored


#========================================================================#


class EpsilonGreedyAgent:
    def __init__(self, k_arms=5, epsilon=0.1):
        self.k = k_arms
        self.epsilon = epsilon

        # Q-values: Our current estimated q-values for each ad - starts at 0
        self.q_values = np.zeros(self.k)

        # N-values: How many times we have selected each ad - starts at 0
        self.action_counts = np.zeros(self.k)

    def choose_action(self):
        """Epsilon-Greedy action selection"""
        # EXPLORE: Roll a number - if less than epsilon, select random ad
        if np.random.random() < self.epsilon:
            return np.random.randint(self.k)
        # EXPLOIT: Otherwise pick ad with highest estimated Q-value
        else:
            return np.argmax(self.q_values)

    def learn(self, action, reward):
        """Updates the estimated value of the chosen ad using incremental avg"""
        # 1. Increment the count for this action
        self.action_counts[action] += 1

        # 2. Update the q-value for the ad using inc. avg formula
        n = self.action_counts[action]
        old_q = self.q_values[action]

        self.q_values[action] = old_q + (1.0 / n) * (reward - old_q)


#========================================================================#


class UCBAgent:
    def __init__(self, k_arms=5, c=2.0):
        self.k = k_arms
        self.c = c # Exploration param

        self.q_values = np.zeros(self.k)
        self.action_counts = np.zeros(self.k)

        # Keep track of the steps taken so far (new)
        self.total_steps = 0

    def choose_action(self):
        """Action based on the upper confidence bound formula"""
        self.total_steps += 1

        # If there is an ad that hasn't show up yet, we must show it first
        # to get the baseline data
        # This prevents 0 in UCB calc
        if 0 in self.action_counts:
            # np.where returns a tuple, [0][0] gets the first index
            # where the count is zero
            return np.where(self.action_counts == 0)[0][0]

        # Calculate UCB for all ads
        # Formula: Q + c * sqrt(ln(t) / N)
        exploration_bonus = self.c * np.sqrt(np.log(self.total_steps) / self.action_counts)
        ucb_values = self.q_values + exploration_bonus

        # Return the action with the highest UCB value
        return np.argmax(ucb_values)

    def learn(self, action, reward):
        """Exactly the same learning rule as epsilon-greedy"""
        self.action_counts[action] += 1
        n = self.action_counts[action]
        old_q = self.q_values[action]

        self.q_values[action] = old_q + (1.0 / n) * (reward - old_q)


#========================================================================#


# 1. Set up env
k_arms = 5
num_steps = 1000 # No. of users visiting the website

# Create 1 env - for comparision (2 env = problem)
env = AdBanditEnv(k_arms=k_arms)

# Instantiate 2 agents
eps_agent = EpsilonGreedyAgent(k_arms=k_arms, epsilon=0.1)
ucb_agent = UCBAgent(k_arms=k_arms, c=2.0)

# Trackers for graphs
eps_cumm_reward = 0
ucb_cumm_reward = 0

eps_avg_hist = []
ucb_avg_hist = []

# 2. The Sim Loop
for step in range(1, num_steps + 1):
    # --- Epsilon Greedy Turn ---
    eps_action = eps_agent.choose_action()
    eps_reward = env.step(eps_action)
    eps_agent.learn(eps_action, eps_reward)

    eps_cumm_reward += eps_reward
    eps_avg_hist.append(eps_cumm_reward / step)

    # --- UCB Turn ---
    ucb_action = ucb_agent.choose_action()
    ucb_reward = env.step(ucb_action)
    ucb_agent.learn(ucb_action, ucb_reward)

    ucb_cumm_reward += ucb_reward
    ucb_avg_hist.append(ucb_cumm_reward / step)


#========================================================================#


import matplotlib.pyplot as plt

# 3. Visualizing the Learning Curve
plt.figure(figsize=(7, 6))
plt.plot(eps_avg_hist, label='Epsilon-Greedy (eps=0.1)', color='blue', alpha=0.8)
plt.plot(ucb_avg_hist, label='UCB (c=2.0)', color='red', alpha=0.8)

# Draw a dashed line showing the theoretical maximum (if we perfectly guessed the best ad from step 1)
best_possible_rate = np.max(env.true_action_values)
plt.axhline(y=best_possible_rate, color='green', linestyle='--', label=f'Optimal Ad Rate ({best_possible_rate:.2f})')

plt.title('Epsilon-Greedy vs. UCB (Average Reward over Time)')
plt.xlabel('Number of Users (Steps)')
plt.ylabel('Average Click Rate')
plt.legend()
plt.grid(True)
plt.show()

"""# RL Traffic Agent"""

import numpy as np
import random

class TrafficEnv:
    def __init__(self, max_cars=5):
        # We cap the cars at max_cars to keep Q-table manageable
        # State represents: (North, South, East, West) queues
        self.max_cars = max_cars

        # Actions: 0 -> North/South Green, 1 -> Left/Right Green
        self.action_space = [0, 1]

        # Start with an empty intersection
        self.state = (0, 0, 0, 0)

        # Track metrics for eval later
        self.total_throughput = 0

    def reset(self):
        """Empties the intersection to start a new episode"""
        self.state = (0, 0, 0, 0)
        self.total_throughput = 0
        return self.state

    def step(self, action):
        """Processes one time step"""
        n, s, e, w = self.state
        # Keep a variable to track the total no. of cars passed in this ep
        cars_passed = 0

        # 1. Let cars pass the intersection on green light
        # Lets assume up to 2 cars can pass thru the light per time step
        pass_rate = 2

        if action == 0: # North/South Green
            # Get no. of cars passed
            passed_n = min(n, pass_rate)
            passed_s = min(s, pass_rate)
            # Update the no. of cars waiting
            n -= passed_n
            s -= passed_s
            # Update the total no. of cars passed
            cars_passed = passed_n + passed_s
        else: # East/West Green
            passed_e = min(e, pass_rate)
            passed_w = min(w, pass_rate)

            e -= passed_e
            w -= passed_w

            cars_passed = passed_e + passed_w

        self.total_throughput += cars_passed

        # 2. New random traffic arrives at the intersxn
        # 30% chance for 1 new car to arrive
        arrival_prob = 0.3

        n = min(self.max_cars, n + (1 if random.random() < arrival_prob else 0))
        s = min(self.max_cars, s + (1 if random.random() < arrival_prob else 0))
        e = min(self.max_cars, e + (1 if random.random() < arrival_prob else 0))
        w = min(self.max_cars, w + (1 if random.random() < arrival_prob else 0))

        # 3. Calculate the reward
        # Reward is the -ve of the total cars waiting.
        # Note that at this point of code, n, s, e, w values have been updated
        total_waiting = n + s + e + w
        reward = -total_waiting

        # Update the current state
        self.state = (n, s, e, w)

        # We will run this continuously in loop so 'done' is false here
        # (we will manually stop the episode after a few steps)
        done = False

        return self.state, reward, done


#========================================================================#


class TrafficQLearningAgent:
    def __init__(self, env, alpha=0.1, gamma=0.9, epsilon=1.0,
                 epsilon_decay=0.99, min_epsilon=0.01):
        self.env = env
        self.alpha = alpha
        self.gamma = gamma
        self.epsilon = epsilon
        self.epsilon_decay = epsilon_decay
        self.min_epsilon = min_epsilon

        # Initialize the Q-table for all 6 * 6 * 6 * 6 possibilities
        # Each key in the Q-table stores a 2-valued array -
        # Q values for action 0 and 1
        self.q_table = {}
        max_c = env.max_cars + 1
        for n in range(max_c):
            for s in range(max_c):
                for e in range(max_c):
                    for w in range(max_c):
                        self.q_table[(n, s, e, w)] = np.zeros(len(env.action_space))

    def choose_action(self, state):
        """Epsilon Greedy Action"""
        if random.uniform(0, 1) < self.epsilon:
            return random.choice(self.env.action_space)
        else:
            return np.argmax(self.q_table[state])

    def learn(self, state, action, reward, next_state):
        """Standard Temporal Difference Update"""
        # Get the best q-value for the next state
        best_next_action_value = np.argmax(self.q_table[next_state])
        # Calculate the actual taget value based on current reward and
        # next state's best q_value (best_next_action_value)
        td_target = reward + (self.gamma * best_next_action_value)
        # Calculate the loss: the target value (actual reward) - curr Q-value
        td_error = td_target - self.q_table[state][action]
        # Update the curr Q-value based on the error calculated
        self.q_table[state][action] += self.alpha * td_error

    def decay_epsilon(self):
        self.epsilon = max(self.min_epsilon, self.epsilon * self.epsilon_decay)


#========================================================================#


# 1. Initialize the env and the agent
env = TrafficEnv(max_cars=5)
agent = TrafficQLearningAgent(env=env, alpha=0.1, gamma=0.9, epsilon=1.0)

num_episodes = 500
steps_per_episode = 100 # Simulating a fixed time block

rewards_history = []
throughput_history = []

# 2. Training Loop
for episode in range(num_episodes):
    # Reset the env at the start of the ep
    current_state = env.reset()
    total_reward = 0

    for step in range(steps_per_episode):
        # Decide which lights to turn green
        action = agent.choose_action(current_state)

        # Advance time by one step
        next_state, reward, done = env.step(action)

        # Learn from the resulting reward
        agent.learn(current_state, action, reward, next_state)

        # Update the current state to the next state
        current_state = next_state
        total_reward += reward

    # Decay epsilon
    agent.decay_epsilon()

    rewards_history.append(total_reward)
    throughput_history.append(env.total_throughput)

"""# Cart-Pole RL"""

import gymnasium as gym
import numpy as np

env = gym.make("CartPole-v1")

bins = [10, 10, 10, 10]
q_table = np.zeros(bins + [env.action_space.n])


#========================================================================#


# Cell 2: Discretization
def discretize(obs):
    upper = [2.4, 3.0, 0.5, 2.0]
    lower = [-2.4, -3.0, -0.5, -2.0]

    ratios = [(obs[i] - lower[i]) / (upper[i] - lower[i]) for i in range(4)]
    new_obs = [int(r * (bins[i]-1)) for i, r in enumerate(ratios)]

    # Clip values to stay within bounds
    new_obs = [min(bins[i]-1, max(0, new_obs[i])) for i in range(4)]

    return tuple(new_obs)


#========================================================================#


# Cell 3: Training
alpha = 0.1
gamma = 0.95
epsilon = 0.1
episodes = 500

rewards = []

for ep in range(episodes):
    obs_raw, _ = env.reset()
    obs = discretize(obs_raw)

    total = 0
    done = False

    while not done:
        if np.random.rand() < epsilon:
            action = env.action_space.sample()
        else:
            action = np.argmax(q_table[obs])

        next_obs_raw, reward, terminated, truncated, _ = env.step(action)
        done = terminated or truncated

        next_obs = discretize(next_obs_raw)

        q_table[obs][action] += alpha * (
            reward + gamma * np.max(q_table[next_obs]) - q_table[obs][action]
        )

        obs = next_obs
        total += reward

    rewards.append(total)

print("Training Done")


#========================================================================#


# Cell 4: Plot
import matplotlib.pyplot as plt

plt.plot(rewards)
plt.xlabel("Episodes")
plt.ylabel("Reward")
plt.title("Episode Reward vs Episodes")
plt.show()

"""# Probabilistic Reasoning Disease"""

# Cell 1: Single Symptom
def bayes(p_d, p_s_d, p_s_nd):
    p_s = p_s_d * p_d + p_s_nd * (1 - p_d)
    return (p_s_d * p_d) / p_s

# Example
print("Posterior:", bayes(0.01, 0.9, 0.05))


#========================================================================#


# Cell 2: Multiple Symptom
def multi_symptoms(p_d, p_s_d, p_s_nd):
    p_s_d_all = np.prod(p_s_d)
    p_s_nd_all = np.prod(p_s_nd)

    p_s = p_s_d_all * p_d + p_s_nd_all * (1 - p_d)

    return (p_s_d_all * p_d) / p_s

# Example
p_d = 0.01
p_s_d = [0.9, 0.8]
p_s_nd = [0.05, 0.1]

print("Posterior (multi):", multi_symptoms(p_d, p_s_d, p_s_nd))


#========================================================================#


# Cell 3: Classification
threshold = 0.5

prob = multi_symptoms(0.01, [0.9,0.8], [0.05,0.1])

if prob > threshold:
    print("Disease Present")
else:
    print("Disease Not Present")